# Generated by Django 3.1 on 2023-01-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('цвят', 'цвят'), ('размер', 'размер')], max_length=100),
        ),
    ]
