# Generated by Django 4.0.6 on 2023-04-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_hidden_desc_product_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
