# Generated by Django 3.1 on 2023-02-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hidden_tags',
        ),
    ]
