# Generated by Django 3.1 on 2023-02-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_hidden_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden_desc',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
